title: Arturo Herrero
description: The personal website of Arturo Herrero
author: Arturo Herrero
url: "https://arturoherrero.com"

markdown: kramdown
permalink: :title/

sass:
  style: :compressed
  sass_dir: assets/css

plugins:
  - jekyll-redirect-from

exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md
