title: Arturo Herrero
description: The personal website of Arturo Herrero
url: "https://arturoherrero.com"

markdown: kramdown
permalink: :title/

sass:
  style: :compressed

plugins:
  - jekyll-redirect-from

exclude: [Gemfile, Gemfile.lock, Guardfile, .gitignore, README.md]
