title: Arturo Herrero
description: The personal blog of Arturo Herrero
url: "http://arturoherrero.com"

markdown: kramdown
permalink: :title/

sass:
  style: :compressed
  sass_dir: assets/sass

gems:
  - jekyll-redirect-from

exclude: [Guardfile, .gitignore, README.md]
