title: Nada Ashraf
title-notes: Notes | Arturo Herrero
description: The personal website of Arturo Herrero.
author: Arturo Herrero
url: "https://nada-ashraf.github.io"

markdown: kramdown
permalink: :title/

collections:
  articles:
    output: true
    permalink: :title/
  notes:
    output: true
    permalink: /notes/:title/
  photos:
    output: true
    permalink: /photos/:title/

sass:
  style: :compressed
  sass_dir: assets/css

plugins:
  - jekyll-redirect-from

exclude:
  - .gitignore
  - .travis.yml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
