title: Arturo Herrero
description: The personal blog of Arturo Herrero
url: "http://arturoherrero.com"

markdown: kramdown
permalink: :title
gems:
  - jekyll-redirect-from
exclude: [Guardfile, .gitignore, README.md]
